### ISSUE TITLE
请问能否补充根据期刊全称补足简称的功能

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/zotero-updateifs#1]
发现使用插件导入题录后，有些题录的期刊简称是缺失的，如果能利用web of science之类的数据库补足就好了，这样在显示里就可以用简称，节约了很大的展示空间

谢谢老师呀

**Comment by redleafnew** [comment]
这个插件不具备这个功能啊，只是更新影响因子的哦。

**Comment by fredericky123** [comment]
> 这个插件不具备这个功能啊，只是更新影响因子的哦。

想着实现这个功能是不是和查询更新if类似，就想着如果能做个类似的插件就好了

**Comment by redleafnew** [comment]
唯问上倒是有期刊缩写，但期刊缩写作用大吗？

**Comment by fredericky123** [comment]
> 唯问上倒是有期刊缩写，但期刊缩写作用大吗？
<img width="187" alt="image" src="https://user-images.githubusercontent.com/13982749/155043638-15a3c84b-1d3f-486c-9189-699683e901f4.png">

这里很长，占了很多空，缩写几个字母就搞定了，看起来很方便简洁

**Comment by redleafnew** [comment]
代码已实现，我再测试一下，明天更新。

**Comment by fredericky123** [comment]
> 代码已实现，我再测试一下，明天更新。

哇，太速度了！感谢感谢！

**Comment by redleafnew** [comment]
更新了，可以测试一下。

**Comment by fredericky123** [comment]
发现个问题如下：期刊名为Management science,结果匹配的为另一个
![image](https://user-images.githubusercontent.com/13982749/155251247-c73fabec-f283-4793-ba6d-6807a2b2f163.png)
![image](https://user-images.githubusercontent.com/13982749/155251273-d2d9fa26-45f3-4549-a4c6-a449c7a0080a.png)

**Comment by fredericky123** [comment]
我的建议是先通过唯问获取匹配到的期刊列表，再根据正则表达式进行精确匹配？因为唯问好像没法实现精确匹配

**Comment by redleafnew** [comment]
对，唯问是不精确匹配，所以需要写正则严格匹配到期刊名称。

**Comment by redleafnew** [comment]
修改了一下，再试一下。

**Comment by redleafnew** [comment]
还有些期刊名和唯问可能不一致，如Zotero中是<code>：</code>，但唯问是<code>-</code>，有的带<code>，</code>也匹配不到。

**Comment by fredericky123** [comment]
目前很完美，我常用的期刊里没有特殊字符的，能解决常见问题就很棒

**Comment by redleafnew** [comment]
欢迎推荐，加星。

**Comment by fredericky123** [comment]
能不能设置一个选项，新导入的题目自动添加if,自动添加缩写呢？

**Comment by redleafnew** [comment]
回头学习一下如何搞，我还不会。好像添加个什么事件。

**Comment by fredericky123** [comment]
> 回头学习一下如何搞，我还不会。好像添加个什么事件。

【Zotero IF 插件】下载链接: 
https://pan.baidu.com/s/1-nIHvhRj_wK_t6LMsNF6rg 提取码: apeh
这里的xpi应该有相关的代码

**Comment by redleafnew** [comment]
好的，很多插件都可以，但我一起懒得弄，我自己需求不大。

**Comment by fredericky123** [comment]
哈哈 这个自动搞好了我真心觉得很方便 用缩写完美了
辛苦韩老师呀

**Comment by fredericky123** [comment]
韩老师，还有个建议，中文期刊的缩写用全称替代吧，不然缩写列为空了
![image](https://user-images.githubusercontent.com/13982749/155283914-db4eac76-5766-47e8-8d86-404adf5b98e0.png)

**Comment by redleafnew** [comment]
代码实现了。我再测试一下。

**Comment by fredericky123** [comment]
或者我觉得逻辑应该是这样，匹配不到缩写的用全称，解决英文匹配不到为空的情况，也解决了中文缩写问题

**Comment by redleafnew** [comment]
我回头更新一下，应该是可以了。

**Comment by redleafnew** [comment]
更新了。

**Comment by fredericky123** [comment]
> 更新了。

立刻用起来~

**Comment by fredericky123** [comment]
![image](https://user-images.githubusercontent.com/13982749/155444250-0ceaf0f6-e6e9-48a9-b655-0a945f2717e2.png)
中科院分区信息为空，这里是正常的么
我发现如果期刊全称为sentence case则会导致匹配不到，比如Academy of management review

**Comment by redleafnew** [comment]
> ![image](https://user-images.githubusercontent.com/13982749/155444250-0ceaf0f6-e6e9-48a9-b655-0a945f2717e2.png) 中科院分区信息为空，这里是正常的么 我发现如果期刊全称为sentence case则会导致匹配不到，比如Academy of management review

是严格匹配的，区分大小写，也是提醒如果匹配不到，可以自己检测大小写，防止后面引用的时候也是大小写不对。

**Comment by redleafnew** [comment]
> 其实这个语句逻辑还可以完善，如果全称检索不到就用issn在唯问上去检索，如果issn也检索不到，用doi的信息去检索期刊，再去查缩写，再查不到就用全称

ISSN的可以考虑，有时间了再搞。
有兴趣可以一块维护插件
后面还计划在Tools添加选项设置：添加条目是不是自动添加影响因子，是通过ISSN检索还是通过期刊名称，如果检索不到是不是用全称代替缩写...

**Comment by fredericky123** [comment]
> > 其实这个语句逻辑还可以完善，如果全称检索不到就用issn在唯问上去检索，如果issn也检索不到，用doi的信息去检索期刊，再去查缩写，再查不到就用全称
> 
> ISSN的可以考虑，有时间了再搞。 有兴趣可以一块维护插件 后面还计划在Tools添加选项设置：添加条目是不是自动添加影响因子，是通过ISSN检索还是通过期刊名称，如果检索不到是不是用全称代替缩写...

我正计划学习一下如何编写xpi

**Comment by redleafnew** [comment]
都把好的插件拿过来修改，主要是JS语言，边用边查。

**Comment by redleafnew** [comment]
> > ![image](https://user-images.githubusercontent.com/13982749/155444250-0ceaf0f6-e6e9-48a9-b655-0a945f2717e2.png) 中科院分区信息为空，这里是正常的么 我发现如果期刊全称为sentence case则会导致匹配不到，比如Academy of management review
> 
> 是严格匹配的，区分大小写，也是提醒如果匹配不到，可以自己检测大小写，防止后面引用的时候也是大小写不对。

这个是匹配的2021基础版的分区信息。http://sci.justscience.cn/details.html?sci=1&id=454显示的是空白，所以没有。

**Comment by fredericky123** [comment]
> http://sci.justscience.cn/details.html?sci=1&id=454

用2021升级版吧，2022以后好像就只公布升级版了

**Comment by redleafnew** [comment]
先不改了，等2022年的出来了再修改。

**Comment by fredericky123** [comment]
嗯嗯，不知道2022啥时候发布
![image](https://user-images.githubusercontent.com/13982749/155452775-f285b50b-6813-4622-9219-170963daccf9.png)

**Comment by fredericky123** [comment]
哦哦 写的是每年年底，那还早啊

**Comment by redleafnew** [comment]
反正也只是个参考作用。

**Comment by fredericky123** [comment]
> 反正也只是个参考作用。

是的，不过直接看期刊属于几区，是不是top还挺直观的

**Comment by fredericky123** [comment]
发现一个小bug，当给已经导入的题录添加note，或是添加附件时，会触发自动更新查询信息，只需要在第一次导入的时候触发就好了

**Comment by redleafnew** [comment]
以后有时间更新一下。

**Comment by fredericky123** [comment]
感谢韩老师的迅速更新，发现一个小问题，如果我选中那三个选项的话，直接右键update，并不能更新，而提前选中那三个设定，则能正常更新

**Comment by fredericky123** [comment]
还有，持续蹲2022中科院的分区信息😁

**Comment by redleafnew** [comment]
> 感谢韩老师的迅速更新，发现一个小问题，如果我 未 选中那三个选项的话，直接右键update，并不能更新，而提前选中那三个设定，则能正常更新

未选中手动右键更新没有问题，只是缩写不会写入。

**Comment by fredericky123** [comment]
> > 感谢韩老师的迅速更新，发现一个小问题，如果我 未 选中那三个选项的话，直接右键update，并不能更新，而提前选中那三个设定，则能正常更新
> 
> 未选中手动右键更新没有问题，只是缩写不会写入。

哦哦，我就是看缩写没变化，理解了，未选中就是只更新IF
