### ISSUE TITLE
文献题目改为首字母大写的改进

### ISSUE THREAD

**Issue by hbzhou530** [redleafnew/zotero-updateifs#10]
感谢韩老师的好工具，节省了许多时间。

关于文献题目改为首字母大写的功能，有一点优化建议。
问题：针对文献题目中有冒号":" 的情况，冒号后的首字母也应该大写。

以[综述文献](https://ieeexplore.ieee.org/document/9044873)、[文献SinGAN](https://ieeexplore.ieee.org/document/9008787)为例。

> 原Title：Deep Learning for Image Super-Resolution: A Survey
> 目前结果 ：Deep learning for image super-resolution: a survey

> 期望结果 ：Deep learning for image super-resolution: **A** survey

> 原Title：SinGAN: Learning a Generative Model From a Single Natural Image
> 目前结果 ：SinGAN: learning a generative model from a single natural image

> 期望结果 ：SinGAN: **L**earning a generative model from a single natural image

**Comment by redleafnew** [comment]
我试一下，请加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4683725/plugin-test

**Comment by hbzhou530** [comment]
群组已添加。

**Comment by redleafnew** [comment]
不是，不是，需要带冒号条目的就可以，太多了，我不知道测试哪个

**Comment by redleafnew** [comment]
一般一个条目中只有一个冒号吧。
而且是英文冒号，后面有空格。

**Comment by redleafnew** [comment]
更新了，试一下。

**Comment by hbzhou530** [comment]
完美！
