### ISSUE TITLE
杂志名称中大小写问题

### ISSUE THREAD

**Issue by SeaCheChe** [redleafnew/zotero-updateifs#12]
up主，遇到一个问题，就是我的一些杂志的名称在中间有大写，就会导致更新信息失败，我也去维问网查了一下，确实网站中间没有大写，所以检索更新失败，是否能更新一个忽略大小写的功能
举例：zotero中杂志名称是RadioGraphics，维问网是Radiographics，就会更新失败

**Comment by SeaCheChe** [comment]
up主，遇到一个问题，就是我的一些杂志的名称在中间有大写，就会导致更新信息失败，我也去维问网查了一下，确实网站中间没有大写，所以检索更新失败，是否能更新一个忽略大小写的功能。
举例：zotero中杂志名称是RadioGraphics，维问网是Radiographics，就会更新失败

**Comment by SeaCheChe** [comment]
好吧，谢谢up主回复

**Comment by hujie12306** [comment]
> 技术上应该不难实现，但是这样会造成很多大小写不规范的杂志题目。所以不暂时不打算做这个功能。可以给唯问提提建议。

能否自动对不规范的的大小写进行矫正

**Comment by redleafnew** [comment]
工具箱有对期刊大小写进行修改的小工具。但修改后还要进行核实，自动大小写转换有可能不对。
<img width="313" alt="20220514104709" src="https://user-images.githubusercontent.com/22135631/168408083-b6259699-3352-4473-86e7-3ae8f7fdb9e3.png">

**Comment by SeaCheChe** [comment]
> 工具箱有对期刊大小写进行修改的小工具。但修改后还要进行核实，自动大小写转换有可能不对。 <img alt="20220514104709" width="313" src="https://user-images.githubusercontent.com/22135631/168408083-b6259699-3352-4473-86e7-3ae8f7fdb9e3.png">

这个toolbox是安装了哪个插件吗？求名称

**Comment by redleafnew** [comment]
就是当前这个插件。

**Comment by hujie12306** [comment]
我是指,能否根据一个标准的刊名库,对仅大小写不同的刊名进行自动校正

**Comment by redleafnew** [comment]
标准的刊名库从哪找呢？功能太复杂了。而且大小写不规范的毕竟不多。

**Comment by hujie12306** [comment]
直接用唯问的名称?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月14日(星期六) 中午11:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [redleafnew/zotero-updateifs] 杂志名称中大小写问题 (Issue #12)





 
标准的刊名库从哪找呢？功能太复杂了。而且大小写不规范的毕竟不多。

**Comment by SeaCheChe** [comment]
> 就是当前这个插件。

<img width="567" alt="image" src="https://user-images.githubusercontent.com/105227871/168409103-6207aac8-08f3-43bc-b23c-3b8c1cde2946.png">
找了半天找到了，但是我的选项里没有您那个选项，只有更改首字母的选项，是版本问题？

**Comment by redleafnew** [comment]
http://sci.justscience.cn/

**Comment by redleafnew** [comment]
> > 就是当前这个插件。
> 
> <img alt="image" width="567" src="https://user-images.githubusercontent.com/105227871/168409103-6207aac8-08f3-43bc-b23c-3b8c1cde2946.png">
> 
> 找了半天找到了，但是我的选项里没有您那个选项，只有更改首字母的选项，是版本问题？

更改期刊名首字母大小写

**Comment by SeaCheChe** [comment]
> http://sci.justscience.cn/

好的，谢谢您
