### ISSUE TITLE
BUG: Journal of Materials Science & Technology 更新错误

### ISSUE THREAD

**Issue by hujie12306** [redleafnew/zotero-updateifs#13]
正确:
![image](https://user-images.githubusercontent.com/61086637/168416918-3a34689a-6a31-46d3-af54-566e5521e542.png)
实际:
![image](https://user-images.githubusercontent.com/61086637/168416923-57ca64c2-0c8b-41c7-a1bb-08e27b1ec643.png)
条目: [导出的条目.zip](https://github.com/redleafnew/zotero-updateifs/files/8692521/default.zip)

**Comment by redleafnew** [comment]
有什么错误？
加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4683725/plugin-test

**Comment by hujie12306** [comment]
错误在于应当是英文JCR分区（档案）实际为C类，其他该有的如影响因子，实际为空白。 已加入群组，见 分类-错误

**Comment by hujie12306** [comment]
另外,还有部分失败的,见 分类-失败

**Comment by redleafnew** [comment]
可以先对照一下从唯问上获取的数据，插件的数据来源是唯问的。

**Comment by hujie12306** [comment]
对照过了,实际
![image](https://user-images.githubusercontent.com/61086637/168419509-1c6dc1fe-67ed-4f0d-acf2-74b58e22c7b6.png)

**Comment by hujie12306** [comment]
实操时,获取数据会先更新为正确数据,然后迅速变成错误的

**Comment by redleafnew** [comment]
这是哪个条目的

**Comment by hujie12306** [comment]
标题:Optimizing synthesis conditions of nanoscale zero-valent iron (nZVI) through aqueous reactivity assessment
期刊: Frontiers of Environmental Science & Engineering

**Comment by hujie12306** [comment]
"失败"分类里的都一样
![image](https://user-images.githubusercontent.com/61086637/168419794-83facace-8c63-40e9-9d96-6e58f96c6dd1.png)

**Comment by hujie12306** [comment]
并且,更新过这类条目后,必须重启,插件才能正常运行,否则会更新失败

**Comment by redleafnew** [comment]
<img width="325" alt="20220514173032" src="https://user-images.githubusercontent.com/22135631/168420058-9fd709c6-9c3c-4ad2-af84-f3880ea5ebf0.png">
C类这个是NJAU这个选项中设置的。看看和后面的是不是放同一个字段了。可以把这个禁用或设为其它字段。

**Comment by redleafnew** [comment]
> 并且,更新过这类条目后,必须重启,插件才能正常运行,否则会更新失败

这个搞不定，升级为6.0后就这样了，问开发者，没有人回复。

**Comment by hujie12306** [comment]
我把它关了
![image](https://user-images.githubusercontent.com/61086637/168420124-780060ab-16b7-474e-9c84-6a950204e855.png)

**Comment by redleafnew** [comment]
我的源代码中没有“C类”，这个数据是从哪获取的。是不是其它插件生成的。

**Comment by hujie12306** [comment]
我不确定,
![image](https://user-images.githubusercontent.com/61086637/168421569-5d9bc035-4e37-45c1-9daa-7e4ce6aa9c53.png)
这是我安装的所有插件

**Comment by hujie12306** [comment]
resource://zotero/bluebird/generators.js:201:9 Zotero.UpdateIFs.updateSelectedItem@chrome://zoteroupdateifs/content/scripts/zoteroupdateifs.js:557:21 reportErrors@chrome://zotero/content/zoteroPane.js:5179:15 oncommand@chrome://zotero/content/standalone/standalone.xul:1:1

(4)(+0000007): Updating database with new item data

(4)(+0000000): Beginning DB transaction 68tZ90uf

(4)(+0000005): UPDATE items SET synced=?, clientDateModified=?, dateModified=? WHERE itemID=? [0, '2022-05-14 10:19:40', '2022-05-14 10:19:40', 4170]

(3)(+0000003): Notifier.trigger('modify', 'item', [4170], {}) queued

(4)(+0000000): SELECT valueID FROM itemDataValues WHERE value=? ['C类']

(4)(+0000035): SELECT valueID FROM itemDataValues WHERE value=? ['科技核心']

(4)(+0000003): DELETE from itemData WHERE itemID=? AND fieldID IN (?,?,?) [4170, 10, 12, 15]

**Comment by hujie12306** [comment]
按照错误日志,应该就是updateif的问题,但不知道到底是什么引起的

**Comment by hujie12306** [comment]
我将中文的关掉
![image](https://user-images.githubusercontent.com/61086637/168422647-b29fbb39-198c-4b09-8854-7d29da8af0e2.png)
可以相对正常更新,但是会显示更新了双倍数量的条目

**Comment by hujie12306** [comment]
> 我的源代码中没有“C类”，这个数据是从哪获取的。是不是其它插件生成的。

"C类"是CSCD的分类
![image](https://user-images.githubusercontent.com/61086637/168426106-d9da48a9-bc44-414e-a2b1-b74c59fb679f.png)
我现在可以确定,这种情况是因为先运行了英文更新,又运行了中文更新,但是各条目的语言并没有问题

**Comment by redleafnew** [comment]
应该是没有对语言进行判断，直接搜索的。

**Comment by redleafnew** [comment]
> > 我的源代码中没有“C类”，这个数据是从哪获取的。是不是其它插件生成的。
> 
> "C类"是CSCD的分类 ![image](https://user-images.githubusercontent.com/61086637/168426106-d9da48a9-bc44-414e-a2b1-b74c59fb679f.png) 我现在可以确定,这种情况是因为先运行了英文更新,又运行了中文更新,但是各条目的语言并没有问题

那就关掉这个吧。
