### ISSUE TITLE
无法更新期刊信息

### ISSUE THREAD

**Issue by pencilheart** [redleafnew/zotero-updateifs#14]
Zotero Report ID：D856665766，[Debug Output.txt](https://github.com/redleafnew/zotero-updateifs/files/8693847/Debug.Output.txt)
代码如上，当选中多条条目进行“从维网更新期刊信息”时，有时不更新if及分区等信息，只可更新“系列标题=无”与“系列文本=无”。

请大佬帮忙查看下是哪里出了问题。

插件设置如下图所示。

![1](https://user-images.githubusercontent.com/61617063/168447891-504ce60d-f840-494d-806b-6af7e9d7c152.png)
![2](https://user-images.githubusercontent.com/61617063/168447895-037d6833-84ad-49aa-bedf-4c6e9f23319e.png)

**Comment by pencilheart** [comment]
猜测是由于网络原因，考虑到基本上IF等信息每年才更新一次，可否参考此代码[hlblade/Zotero_IF: Add impact factor for Zotero collections in batches](https://github.com/hlblade/Zotero_IF)，将“维问”中的全部期刊信息爬取到xpi插件文件中形成库，届时需要的话直接从插件中寻找匹配，不知是否可行？

**Comment by redleafnew** [comment]
应该不是网络的原因，现在是更新一两个就不行了，重启一下就可以了，过一会儿就又不行了。

本地数据库有这个想法，后面再说了。

**Comment by redleafnew** [comment]
科研通的数据适合抓取，我回头试一下这个数据源的。

**Comment by pencilheart** [comment]
感谢大佬！

**Comment by ytdhblk227** [comment]
我也遇到了这个问题，期待大佬更新。

**Comment by redleafnew** [comment]
好像与数据源没有关系？你们用的Zotero是测试版的还是正式版的？

**Comment by pencilheart** [comment]
> 好像与数据源没有关系？你们用的Zotero是测试版的还是正式版的？

zotero 6.0正式版

**Comment by redleafnew** [comment]
比较难办，我是测试版的时候问题比较大，而且报错的时候，切换为科研通的数据也是不行。
同时说不准啥时候就不行了。

**Comment by pencilheart** [comment]
看来本地数据库可能是最优解了

**Comment by redleafnew** [comment]
等出来最新的影响因子表和中科院分析后再说了。

**Comment by pencilheart** [comment]
好嘞大佬

**Comment by crazyi** [comment]
回退到0.8.0版就可以了，不会每次只能打开更新一次

**Comment by redleafnew** [comment]
如果有中科院分区表，可以改为本地数据了，影响因子我这有。

**Comment by redleafnew** [comment]
谁那有中科院分区表、中文期刊影响因子表的excel格式数据？

**Comment by redleafnew** [comment]
本地数据版即将发布在：https://github.com/redleafnew/zotero-updateifsL，本issue关闭。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE
已经上传为easyScholar版本。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifs/releases/tag/0.93.5 试一下看还有没有问题。

**Comment by pencilheart** [comment]
测试了下，目前无问题，辛苦大佬了
