### ISSUE TITLE
是否可以增加SCI影响因子的设置范围

### ISSUE THREAD

**Issue by sheshen22** [redleafnew/zotero-updateifs#15]
![image](https://user-images.githubusercontent.com/104003939/168462862-827b50a3-ab2f-4cc2-9f68-d2793abfa55f.png)
是否可以将系列、系列标题、系列文本同样加到可以自由选择的选项里面，谢谢~

**Comment by redleafnew** [comment]
回头我增加上。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifs/releases/tag/0.93.0
没有加系列，涉及增加的东西有点多，如果需要可以在Zotero修改配置（Zotero中的Edit-Preference-Advanced-Config Editor中）extensions.updateifs.*-field。
