### ISSUE TITLE
期刊缩写带点格式和不带点格式，以及期刊缩写信息源的选择

### ISSUE THREAD

**Issue by dawnlh** [redleafnew/zotero-updateifs#16]
非常感谢大佬的开源付出，极大方便了科研狗！还有两个使用中的问题请教大佬：

（1）请问能不能加个小工具，可以切换期刊缩写的带点格式和不带点格式（因为不同期刊要求不同），即 Photonics Res 转换为 Photonics Res. ，当然这个可能比较麻烦，因为有的单词没缩写不需要加点（比如这里的 Photonics）。
（2） 这个缩写信息源能不能做成可选项，因为我发现现在有些缩写 sci.justscience 其实不太对，比如  IEEE Transactions on Image Processing，给的缩写为 IEEE T Image Process，但是正常的应该是  IEEE Trans Image Process。我觉得这个可以参考 Jabref 软件获取缩写的信息源，那个比较准，他们维护了一个缩写的list，具体的信息源在这 https://abbrv.jabref.org/journals/ 。

其实上面两个功能好像jabref都有，但是如果能在zotero实现会方便很多，就不用来回导出 bib 转换折腾了。

感谢大佬！膜拜

**Comment by redleafnew** [comment]
期刊的缩写来源于唯问。选择是否带点的可以在Word中设置使用MEDILINE实现。
![zotero_ntlWegTJyJ](https://user-images.githubusercontent.com/22135631/172352397-74f53d47-9b26-41e9-98b2-2a96a406d9fb.png)

另外期刊缩写在https://github.com/redleafnew/delitemwithatt中使用的是本地数据。如果可以将 <https://abbrv.jabref.org/journals/>数据下载下来，做成json格式，应该可以整合进去。
后期再说了。

**Comment by dawnlh** [comment]
感谢老师回复！因为我一般是用 latex （overleaf）写论文，不太用word，所以如果能直接把那个 journal abbr 字段改成带点的导出来 bib 文件放在 latex 里面用就会更方便一点，当然，只是一个小需求啦，没有也影响不大，可以通过别的途径。 缩写来源方面也期待本地版本的后续更新！

**Comment by redleafnew** [comment]
你方便把这个网址上所有的领域csv下来整理一下吗？搞成两列或三列，分别是：

全称 缩写带点 缩写不带点 

或是

全称 缩写带点

我们整合进软件。

**Comment by dawnlh** [comment]
我把 jabref 里面的 general 那个 list 转换成了“全称 缩写带点 缩写不带点” 的csv表格， [journal_abbreviations_general_formated.csv](https://github.com/redleafnew/zotero-updateifs/files/8888864/journal_abbreviations_general_formated.csv) 。其他几个单独领域的 list 大部分都包含在这个list里面了（不过有些期刊可能单独领域的 list 里面会更准确，但是条目太多，我没法一个个确认。我们可以自己维护 general 这个 list，大家发现了问题提 issue 更新一下就行） 这是转换格式用的代码。https://gist.github.com/dawnlh/1d44df53b1708077d420ef25e939cd4b

**Comment by dawnlh** [comment]
顺便问下，使用本地数据的只有插件 [delitemwithatt](https://github.com/redleafnew/delitemwithatt) 是吧

**Comment by redleafnew** [comment]
现在本地数据的是在Delitem，
要麻烦@l0o0 做成接口，回头整合进[UpdateIFsE](https://github.com/redleafnew/zotero-updateifsE)中

**Comment by dawnlh** [comment]
好的，期待一下！

**Comment by redleafnew** [comment]
@dawnlh
目前期刊缩写数据库只有5000多条数据，还是有点少，[Delitem插件](https://github.com/redleafnew/delitemwithatt)本地数据有1万多条。
https://github.com/redleafnew/delitemwithatt/blob/77c53a42127ec07b5c94a1ed11c1ff8126704d67/chrome/content/scripts/delitem.js#L650-L13662，但没有带点的数据。

**Comment by redleafnew** [comment]
已更新，<https://github.com/redleafnew/zotero-updateifsE/releases>， 后续讨论请到<https://github.com/redleafnew/zotero-updateifsE>。
