### ISSUE TITLE
请问“JCR: /以上面为准Q1”是什么意思

### ISSUE THREAD

**Issue by RobRicardo** [redleafnew/zotero-updateifs#17]
![image](https://user-images.githubusercontent.com/108347697/176857623-17ae943f-1170-4049-b13a-c8a7bdf5a4ed.png)
请问这个“/以上面为准”是什么意思？
同时，这两天更新期刊信息有时会更新失败，要怎么解决？

**Comment by redleafnew** [comment]
哪个杂志？试试https://github.com/redleafnew/zotero-updateifsE版本

**Comment by RobRicardo** [comment]
> 哪个杂志？试试 https://github.com/redleafnew/zotero-updateifsE 版本

Mechanism and Machine Theory

**Comment by redleafnew** [comment]
![msedge_huClU9yq6i](https://user-images.githubusercontent.com/22135631/176986952-9ac9bd6e-541f-4925-b949-5e779823e1ae.png)
代码中匹配的JCR分区后面的文字是其分区，所以出现了这个问题。
使用的是唯问的数据，更新是经常失败，重启软件后会好一会儿，但一会儿就又不行了，原因不知道。

使用easyScholar版本吧。

**Comment by RobRicardo** [comment]
> http://sci.justscience.cn/details.html?sci=1&id=4868 ![msedge_huClU9yq6i](https://user-images.githubusercontent.com/22135631/176986952-9ac9bd6e-541f-4925-b949-5e779823e1ae.png) 代码中匹配的JCR分区后面的文字是其分区，所以出现了这个问题。 使用的是唯问的数据，更新是经常失败，重启软件后会好一会儿，但一会儿就又不行了，原因不知道。
> 
> 使用easyScholar版本吧。

好的，谢谢大佬

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifs/releases/tag/0.93.5 试一下看还有没有问题。
