### ISSUE TITLE
中文期刊显示影响因子

### ISSUE THREAD

**Issue by Sifan798** [redleafnew/zotero-updateifs#18]
![image](https://user-images.githubusercontent.com/59358565/177971056-0ede6576-6a27-4d51-a1f2-c2c9dc071854.png)
类似于唯问影响因子更新，是否可以添加影响因子值（复合和综合）。人文社科也很需要，一人血书求。💕😘

**Comment by redleafnew** [comment]
唯问版的是有影响因子的好像。

**Comment by Sifan798** [comment]
是的，但是唯问更新老出错，显示无法获取。easyScholar可以，但是中文没有影响因子栏目，可以搞一下easyScholar😜

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.2.0
