### ISSUE TITLE
[Problems] 更新失效

### ISSUE THREAD

**Issue by bianhaotian** [redleafnew/zotero-updateifs#19]
可以在justscience上搜索到，现在更新不出来了，希望能看看数据接口是不是有问题。Ps. 相比于从easyscholar上获取if，justscience的分区更全，从justscience获取期刊信息对我来说更重要。

**Comment by redleafnew** [comment]
需要哪个分区？

**Comment by redleafnew** [comment]
中科院的分区从今年开始只有升级版了好像。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifs/releases/tag/0.93.5 试一下看还有没有问题。

**Comment by bianhaotian** [comment]
redleafnew：


        您好！我已收到您的邮件。经测试，已经可以正常从justscience进行期刊更新了。从justscience更新的JCR分区会有两个不同类目下的分区信息，更全。
      
       感谢您对Zotero开源插件的付出，updateif插件对大多数科研工作者都是福音。最后，祝身体安康，研究顺利！


2022-07-24


---- Replied Message ----
| From | ***@***.***> |
| Date | 07/24/2022 20:11 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [redleafnew/zotero-updateifs] [Problems] 更新失效 (Issue #19) |

https://github.com/redleafnew/zotero-updateifs/releases/tag/0.93.5 试一下看还有没有问题。

**Comment by redleafnew** [comment]
那关闭issue了

**Comment by Chikit-L** [comment]
> 那关闭issue了

大佬您好，打扰一下，zotero-updateifs现在又不能用了（justscience可以正常访问），请问有更新计划吗
