### ISSUE TITLE
建议将title批量转为sentence case加入toolbox，成为右键选项

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/zotero-updateifs#2]
目前还在搞毕设，强烈建议老师优先实现这个功能，方便批量转换

**Comment by redleafnew** [comment]
批量转换多选条目就可以了。

**Comment by fredericky123** [comment]
感谢老师
![image](https://user-images.githubusercontent.com/13982749/157182872-15e964df-3ab2-4781-bc37-0c012515feb6.png)
ce's测试发现，每个标题没有分行，不知道方不方便每个题目分个行，方便对比确认是否需要个别专有名词改回来
另外，这个右键里没有，要是选中条目后右键有更方便哎

**Comment by redleafnew** [comment]
![zotero_tDB411NHc0](https://user-images.githubusercontent.com/22135631/157187498-1012a257-aed6-4995-9b63-18260d48136f.png)
代码中是有换行的，但是调用的Zotero.ProgressWindow可能把换行给删除了，或是改为上面的提醒模式。

**Comment by fredericky123** [comment]
这种其实一目了然，也挺好，因为修改为需要人工check一下
能否增加一个导入题录后自动修改为sentence的option呢
这样省的自己每次手动转换了，只需要check一下

**Comment by redleafnew** [comment]
@l0o0 有办法这个函数支持换行吗？

**Comment by redleafnew** [comment]
右键和导入时自动转换不添加了。

**Comment by fredericky123** [comment]
> @l0o0 有办法这个函数支持换行吗
如果这个函数能实现换行且能实现自动修改的功能，就太方便了
只需要鼠标悬停在那个窗口，就可以check，移走鼠标就完成了。

**Comment by redleafnew** [comment]
太智能了不会。

**Comment by redleafnew** [comment]
如果需要改成js提示框，可以将源代码修改为这样。
  Zotero.UpdateIFs.showPopUP(alertInfo, 'finished'); 对应右下角的提示。
        alert(result); 对应js提醒。
![Code_pRXrv9aALV](https://user-images.githubusercontent.com/22135631/157190497-6584332d-15d7-4c6e-b34f-d677bab3076f.png)

**Comment by fredericky123** [comment]
> 如果需要改成js提示框，可以将源代码修改为这样。 Zotero.UpdateIFs.showPopUP(alertInfo, 'finished'); 对应右下角的提示。 alert(result); 对应js提醒。 ![Code_pRXrv9aALV](https://user-images.githubusercontent.com/22135631/157190497-6584332d-15d7-4c6e-b34f-d677bab3076f.png)

好的，期待一下@l0o0能解决那个函数换行的问题

**Comment by l0o0** [comment]
```html
<description style="white-space: pre-wrap;">
XXX
</description>
```
可以设置样式参数，不过我看`addDescription`并没有相应的参数修改默认样式。
不过我不知道是不是可以设置 CSS 来实现
```css
hbox.zotero-progress-item-hbox > description {
  white-space: pre-wrap;
}
```
这个 CSS 文件 overlay.css 可以在 skin 的目录里。后面我看到这个 CSS 文件需要手动加载，应该是行不通。

我测试了代码，发现有些换行是可以识别的。如果换行一多，就自动换成空格了。我怀疑是不是窗口大小做了限制
```javascript
    var progressWindow = new Zotero.ProgressWindow({closeOnClick:true});
    progressWindow.changeHeadline("Hello");
    progressWindow.addDescription("1111111111111111\n1111111111\n1111111111\n1111111111111\n1111111111\n1111111111111111\n1111111111111111\n1111111111\n111111111");
    progressWindow.show();
    progressWindow.startCloseTimer(4000);
```
![图片](https://user-images.githubusercontent.com/2743744/157352892-ee6399f6-2626-4dce-9ac5-2886916ae725.png)

**Comment by redleafnew** [comment]
这个在哪修改的，复制一个 overlay.css到skin中？完全不懂。

**Comment by l0o0** [comment]
我的想法是有这几种方法
1. 增加 description 元素时，直接把样式写进去。这个不好操作
2. 写一个css文件，这个进度XUL调用css文件，更新样式。这个也不好操作，因为要把css文件加载到 zotero progressWindow.xul里，这个也不好操作

如果不想改源码，或者自己写一个，就这样吧

**Comment by redleafnew** [comment]
就这样了。多谢。

**Comment by redleafnew** [comment]
<img width="194" alt="zotero_WOT9sOL4gG" src="https://user-images.githubusercontent.com/22135631/157657607-beb019a7-3f20-43a4-b336-36854bb56a08.png">
 ZotFile重命名多条的时候，会显示这样，回头瞧瞧看怎么搞的。

**Comment by fredericky123** [comment]
> <img alt="zotero_WOT9sOL4gG" width="194" src="https://user-images.githubusercontent.com/22135631/157657607-beb019a7-3f20-43a4-b336-36854bb56a08.png">
> 
> ZotFile重命名多条的时候，会显示这样，回头瞧瞧看怎么搞的。

这个pdf和链接的logo不知道怎么搞的，那个作为对齐的标志，很赞

**Comment by redleafnew** [comment]
是不是应该使用这个函数：` itemProgress: new this.progressWin.ItemProgress(icon_pdf, OS.Path.basename(path))` 这个ZotFile中的。前面是图标，后面是显示的内容。
而不是：`progressWindow.addDescription(alertInfo);` 这个是我们现在用的。

**Comment by redleafnew** [comment]
<img width="194" alt="zotero_WOT9sOL4gG" src="https://user-images.githubusercontent.com/22135631/157673844-6df59c00-6b71-45fa-9645-f08b5731a3b5.png">
果然是可以的。

**Comment by fredericky123** [comment]
> <img alt="Code_EeyirBRPrn" width="189" src="https://user-images.githubusercontent.com/22135631/157673982-4b717c78-0857-4551-86b1-00abc09a1f8d.png">
> 
> 果然是可以的。

哇！期待！我在想是否有journal article的logo，转换前和转换后的题目之前是不是都加个logo，比用->显示更清晰
![image](https://user-images.githubusercontent.com/13982749/157674341-fd56d9f2-0e08-4c3d-9c65-800b2554d4f3.png)

**Comment by redleafnew** [comment]
你来设计两个icon吧，我试试。大小和chrome://zotero/skin/treeitem-attachment-pdf.png中的一致。

**Comment by fredericky123** [comment]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/13982749/157675984-593348da-96cc-414e-be0c-ec36f700be7a.png">
我检索到了zotero自带的icon，建议第一个用bibsonomy_icon，第二个用s2_icon，不知道是否合适

> 你来设计两个icon吧，我试试。大小和chrome://zotero/skin/treeitem-attachment-pdf.png中的一致。

**Comment by redleafnew** [comment]
发上来吧，我电脑上没有这两个图标。大小应该是16×16

**Comment by fredericky123** [comment]
![bibsonomy_icon](https://user-images.githubusercontent.com/13982749/157677248-1e5cecef-878c-4875-8fe6-bcab3e0400a0.png)
![s2_icon](https://user-images.githubusercontent.com/13982749/157677297-0c31367d-94fa-4b29-8bea-e3bc78104c09.png)

**Comment by fredericky123** [comment]
https://www.iconfont.cn/search/index?searchType=icon&q=new&page=1&tag=&fromCollection=-1&fills=

**Comment by fredericky123** [comment]
> <img alt="Y2HL9aZi6V" width="188" src="https://user-images.githubusercontent.com/22135631/157680843-433ac1f9-c161-4f3b-8084-11d40fb88bde.png">

一目了然，非常完美了！

**Comment by redleafnew** [comment]
题目上还要交待一下，不然不知道是什么意思。

**Comment by fredericky123** [comment]
![废旧](https://user-images.githubusercontent.com/13982749/157719430-56392586-d38e-43b7-97f8-b486de1e96d5.png)
![新品](https://user-images.githubusercontent.com/13982749/157719441-2b2ea209-78de-4ecd-bad8-fe805eff1b56.png)
或者这一对

**Comment by fredericky123** [comment]
![更新](https://user-images.githubusercontent.com/13982749/157720358-be687b6b-7385-4a2f-960f-2015b6a0dcea.png)
这个更新图标也不错

**Comment by redleafnew** [comment]
我打算用这个和你这个两个绿箭头的
![1-11112Q43S5-50](https://user-images.githubusercontent.com/22135631/157793746-87806154-257c-4f0d-b14f-6fa2c0d0ab93.png)

**Comment by fredericky123** [comment]
> 我打算用这个和你这个两个绿箭头的 ![1-11112Q43S5-50](https://user-images.githubusercontent.com/22135631/157793746-87806154-257c-4f0d-b14f-6fa2c0d0ab93.png)

很完美，大家一看应该就能明白

**Comment by fredericky123** [comment]
尺寸要是大了我可以重新上传

**Comment by redleafnew** [comment]
![MRcS1NNbrC](https://user-images.githubusercontent.com/22135631/157797327-caa25458-1b76-4e37-8dcb-10c2976b6b97.png)
最终效果

**Comment by fredericky123** [comment]
> ![MRcS1NNbrC](https://user-images.githubusercontent.com/22135631/157797327-caa25458-1b76-4e37-8dcb-10c2976b6b97.png) 最终效果 ![D7YIme72qt](https://user-images.githubusercontent.com/22135631/157797585-baa31677-d4ac-434d-becd-715f3dd49b4c.png)

蛮好蛮好，期待发布，赶紧用上

**Comment by fredericky123** [comment]
”题目已改为句首字母大写“？
题目大小有点奇怪

**Comment by l0o0** [comment]
对于图标，我之前保存了一套 Zotero 使用的那套[famfamfam图标集](http://www.famfamfam.com/archive/silk-icons-thats-your-lot)，开源是免费使用的，后面说不定能用到。

**Comment by redleafnew** [comment]
> ”题目已改为句首字母大写“？ 题目大小有点奇怪

Zotero中文简体版本中称为：标题大写和句首大写。因此改为了：句首大写。
![zotero_g7A2uZIpiI](https://user-images.githubusercontent.com/22135631/157829632-8f87a962-50e6-42a2-a424-5c684aae7c6d.png)


> ”题目已改为句首字母大写“？ 题目大小有点奇怪

**Comment by fredericky123** [comment]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/13982749/157830243-94faf76d-e94d-428b-ab8a-dc3cd6142cb4.png">
安装怎么提示不兼容

**Comment by redleafnew** [comment]
打包工具有问题，重新上传了，再试一下。

**Comment by fredericky123** [comment]
> 打包工具有问题，重新上传了，再试一下。

可以了，感谢~

**Comment by fredericky123** [comment]
一个小小的疑惑，当一次选中十个题目进行sentence case的转换时，提示窗口会超过屏幕所能容纳，且无法上下滚动查看信息，这个提示信息窗口有能设置为滚动查阅的可能吗？

**Comment by redleafnew** [comment]
我不会设置这个工具条，你看看在Zotero或ZotFile中有这样的窗口吗？有的话我再去找找源代码。

**Comment by fredericky123** [comment]
> 我不会设置这个工具条，你看看在Zotero或ZotFile中有这样的窗口吗？有的话我再去找找源代码。

我去zotfile问问

**Comment by fredericky123** [comment]
请问能否为title 转换为sentence设置一个快捷键，这个用的还挺频繁的，比如ctrl + t （title）
这个xpi设置了快捷键，供参考
下载链接: 
https://pan.baidu.com/s/1-nIHvhRj_wK_t6LMsNF6rg 提取码: apeh

**Comment by redleafnew** [comment]
试了试，搞不成，暂时不弄了。
快捷键可以结合Quicker来弄。

**Comment by redleafnew** [comment]
好像可以了，设置为Ctrl + T？ 
其它功能需要设置吗？

**Comment by fredericky123** [comment]
> 好像可以了，设置为Ctrl + T？ 其它功能需要设置吗？

其他我倒使用频率不高，听老师安排~

**Comment by fredericky123** [comment]
![image](https://user-images.githubusercontent.com/13982749/158181434-be84c8da-17a5-49f2-8bb6-1622c24c38fb.png)
文字重复了？

**Comment by fredericky123** [comment]
<img width="442" alt="image" src="https://user-images.githubusercontent.com/13982749/158540345-9c0ebed7-4a60-4766-bef9-26d25dca9f44.png">
这样改完安装时出现了错误
![image](https://user-images.githubusercontent.com/13982749/158540493-3418fede-8484-4a01-af6f-2b13ca29d787.png)

**Comment by fredericky123** [comment]
> ![image](https://user-images.githubusercontent.com/13982749/158181434-be84c8da-17a5-49f2-8bb6-1622c24c38fb.png) 文字重复了？

Mac Os下ctrl对应的command键，这个提示说明可以按系统写下，不过不写的话mac用户估计也能试出来

**Comment by redleafnew** [comment]
> <img alt="image" width="442" src="https://user-images.githubusercontent.com/13982749/158540345-9c0ebed7-4a60-4766-bef9-26d25dca9f44.png">
> 
> 这样改完安装时出现了错误
> ![image](https://user-images.githubusercontent.com/13982749/158540493-3418fede-8484-4a01-af6f-2b13ca29d787.png)

是打包软件的问题，建议用7zip。

**Comment by redleafnew** [comment]
> > ![image](https://user-images.githubusercontent.com/13982749/158181434-be84c8da-17a5-49f2-8bb6-1622c24c38fb.png) 文字重复了？
> 
> Mac Os下ctrl对应的是command键，这个提示说明可以按系统写下，不过不写的话mac用户估计也能试出来

源代码中我修改过，但没有打包。

**Comment by fredericky123** [comment]
试了半天，还是没成功ε=(´ο｀*)))
mac下的7 zip为concole格式，完全没搞懂怎么用
https://www.7-zip.org/download.html
将自己所用压缩软件的压缩格式改为7zip尝试，还是提示不兼容
![image](https://user-images.githubusercontent.com/13982749/158544991-445bd23b-bafe-4ea5-83b3-131f9869944a.png)

**Comment by redleafnew** [comment]
一般是zip，改名即可。

**Comment by redleafnew** [comment]
![QQ图片20220316162802](https://user-images.githubusercontent.com/22135631/158548064-70da9276-9025-439e-a2a4-c5bc76a6dfc6.png)
或是按这个，从源代码启动。

**Comment by fredericky123** [comment]
> 一般是zip，改名即可。

7z压出来也是zip格式，搞不定了，期待老师下次累积更新的时候加入这几句代码吧

**Comment by redleafnew** [comment]
要手动改扩展名，从zip改为xpi

**Comment by fredericky123** [comment]
> 要手动改扩展名，从zip改为xpi

xpi先解压，成为文档，用sublime修改js，保存后，压缩为zip，然后修改格式为xpi，再zotero加载，就还是不兼容

**Comment by fredericky123** [comment]
https://www.bilibili.com/read/cv9870017
看了这里，提示解压后再修改会失败，需要在压缩文件里直接修改

**Comment by fredericky123** [comment]
最后发现mac下那个betterzip的软件也不能直接保存zip文件
还是换成win上修改的

**Comment by redleafnew** [comment]
![zotero_9540lUxikE](https://user-images.githubusercontent.com/22135631/158718494-cd841a0c-c4d4-439d-b70b-4ab549ad7933.png)
后面打算做个这个，在题目中查找，替换。

**Comment by redleafnew** [comment]
> > <img alt="image" width="442" src="https://user-images.githubusercontent.com/13982749/158540345-9c0ebed7-4a60-4766-bef9-26d25dca9f44.png">
> > 这样改完安装时出现了错误
> > ![image](https://user-images.githubusercontent.com/13982749/158540493-3418fede-8484-4a01-af6f-2b13ca29d787.png)
> 
> 是打包软件的问题，建议用7zip。

麻烦你把这段代码发给我吧，我加进去。

**Comment by fredericky123** [comment]
> > > <img alt="image" width="442" src="https://user-images.githubusercontent.com/13982749/158540345-9c0ebed7-4a60-4766-bef9-26d25dca9f44.png">
> > > 这样改完安装时出现了错误
> > > ![image](https://user-images.githubusercontent.com/13982749/158540493-3418fede-8484-4a01-af6f-2b13ca29d787.png)
> > 
> > 
> > 是打包软件的问题，建议用7zip。
> 
> 麻烦你把这段代码发给我吧，我加进去。

            new_title = new_title.replace('china', 'China'). // 替换china
                     replace('chinese', 'Chinese'). // 替换chinese
                     replace('america', 'America'). // 替换america
                     replace('english', 'English'). // 替换english
                     replace('england', 'England') // 替换england
                     replace('india', 'India') // 替换india

**Comment by fredericky123** [comment]
建议将这里command+t的快捷键更新为command+option+t (ctrl+alt+t)
与https://github.com/redleafnew/delitemwithatt/releases 一致
日后想要自定义快捷键也可优先考虑ctrl+alt+...

**Comment by redleafnew** [comment]
后面更新其它功能时再说了

**Comment by fredericky123** [comment]
没问题，留个备注就行，感激~
