### ISSUE TITLE
[Problem]多个条目更新时发生错误

### ISSUE THREAD

**Issue by dreamMilk** [redleafnew/zotero-updateifs#20]
# 运行环境
多个条目中存在寻找不到期刊信息（指单独更新显示期刊信息没有找到）的条目

# 进行的操作
一次性选择多个条目后右键选择“从easyScholar更新期刊信息”

# 出现的错误
原本显示期刊信息没有找到的条目，它的信息会被该条目的前一个条目信息覆盖

# 例子
这个是寻找不到期刊信息的条目
![image](https://user-images.githubusercontent.com/42259923/180218805-68a310fa-cf25-4116-b46c-128fc4db0b0d.png)

这个是操作后的样子
![image](https://user-images.githubusercontent.com/42259923/180219043-2328efd4-575b-468b-b550-fb2a17b2c274.png)

**Comment by redleafnew** [comment]
加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4683725/plugin-test

**Comment by dreamMilk** [comment]
已上传

**Comment by dreamMilk** [comment]
> 加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4683725/plugin-test

已上传

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.3.0
已更新。

**Comment by redleafnew** [comment]
有问题到那个项目提issue，此条关闭。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifs/releases/tag/0.93.5 试一下看还有没有问题。
