### ISSUE TITLE
使用过程中还是有很多文献匹配不上IF

### ISSUE THREAD

**Issue by lmlm1995** [redleafnew/zotero-updateifs#21]
使用过程中还是有很多文献匹配不上IF，我是肿瘤学方面的，发现连大名鼎鼎的《Journal of Clinical Oncology》也匹配不上，不知道是不是应该进行相关设置才能更好的使用，目前我是默认设置。
       当然，感觉IF也是迷一样的东西，我还有其他几个软件/插件，同一篇文献各家给出的IF都不一样。

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/181390603-64077ac2-9145-41ac-81a0-0eac2379336f.png)
可以的啊

**Comment by redleafnew** [comment]
这个插件数据来源于http://sci.justscience.cn/?q=Journal+of+Clinical+Oncology&sci=1，
另外easyScholar版本也可以的。影响因子查询、数据目录，配置目录及其它小工具：https://github.com/redleafnew/zotero-updateifsE
不行的话设置一下条目语言，
导出附件，删除条目时删除附件，批量修改语言为e-US, 更新期刊缩写的插件：https://github.com/redleafnew/delitemwithatt

**Comment by lmlm1995** [comment]
这个应该是爬网抓取数据的吧？
有没有可能把每年发布的数据直接整合到插件，直接从插件调取数据，不用爬网？


国内有一款软件《医学文献王》好像是这么做的。导入到它里面的文献基本能显示IF。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/zotero-updateifs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 上午7:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/zotero-updateifs] 使用过程中还是有很多文献匹配不上IF (Issue #21)





 
这个插件数据来源于http://sci.justscience.cn/?q=Journal+of+Clinical+Oncology&amp;sci=1，
 另外easyScholar版本也可以的。影响因子查询、数据目录，配置目录及其它小工具：https://github.com/redleafnew/zotero-updateifsE
 不行的话设置一下条目语言，
 导出附件，删除条目时删除附件，批量修改语言为e-US, 更新期刊缩写的插件：https://github.com/redleafnew/delitemwithatt

**Comment by redleafnew** [comment]
原来想过搞本地数据版的，但会造成插件体积过大，所以都是用的网络数据，现在是唯问或easyScholar。

**Comment by redleafnew** [comment]
如无进一步反馈，则关闭。

**Comment by redleafnew** [comment]
现在应该都查不到了，可以用这个。
影响因子查询、数据目录，配置目录及其它小工具：https://github.com/redleafnew/zotero-updateifsE
