### ISSUE TITLE
JavaScript Error: "ReferenceError: module is not defined

### ISSUE THREAD

**Issue by opiado** [redleafnew/zotero-updateifs#22]
[JavaScript Error: "ReferenceError: module is not defined" {file: "chrome://zoteroupdateifs/content/scripts/zoteroupdateifs.js" line: 1253}]
@chrome://zoteroupdateifs/content/scripts/zoteroupdateifs.js:1253:1
reportErrors@chrome://zotero/content/zoteroPane.js:5245:15
oncommand@chrome://zotero/content/standalone/standalone.xul:1:1

**Comment by redleafnew** [comment]
加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4683725/plugin-test

**Comment by opiado** [comment]
> 加入Zotero群组，将条目拖动到群组中，方便测试：https://www.zotero.org/groups/4683725/plugin-test

是所有条目都看不到if和分区

**Comment by redleafnew** [comment]
重新安装一下插件试试。或是安装
影响因子查询、数据目录，配置目录及其它小工具：https://github.com/redleafnew/zotero-updateifsE

**Comment by opiado** [comment]
> 重新安装一下插件试试。或是安装 影响因子查询、数据目录，配置目录及其它小工具：https://github.com/redleafnew/zotero-updateifsE

重装好多遍都不行，用easyScholar可以啦，感谢~

**Comment by llity** [comment]
发现，有时候无法更新数据。试一试easyscholar
