### ISSUE TITLE
Justscience版全部中英文期刊无法更新数据

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [redleafnew/zotero-updateifs#23]
请问是不是Justscience接口失效了呀，所有期刊均无法更新期刊信息，但是Justscience官网能手动查找到

**Comment by redleafnew** [comment]
唯问的页面可能经过改版了，以前匹配的正则表达式失效了。
有时间再修复。
可以先用影响因子查询、数据目录，配置目录及其它小工具：https://github.com/redleafnew/zotero-updateifsE

**Comment by yuzixieshouhuajiaqi** [comment]
好的，感谢～

**Comment by ENIGMA-K** [comment]
期待修复~

**Comment by redleafnew** [comment]
已经更新，修复，可以试试。

不过还是推荐用easyScholar版本的。
影响因子查询、数据目录，配置目录及其它小工具：https://github.com/redleafnew/zotero-updateifsE

**Comment by yuzixieshouhuajiaqi** [comment]
感谢，辛苦了~
