### ISSUE TITLE
更新失败

### ISSUE THREAD

**Issue by HeanyGao** [redleafnew/zotero-updateifs#24]
今天点击就显示更新失败了
http://sci.justscience.cn/ 这个网址好像也打不开了
请问有解决办法吗

**Comment by redleafnew** [comment]
唯问应该是又改版了，可以用easyScholar版的。影响因子查询、数据目录，配置目录及其它小工具：https://github.com/redleafnew/zotero-updateifsE

**Comment by HeanyGao** [comment]
已更换，现在是好的了，十分感谢！

**Comment by redleafnew** [comment]
唯问版也已经更新，现在应该可以了。
