### ISSUE TITLE
最新版的一些问题

### ISSUE THREAD

**Issue by Chikit-L** [redleafnew/zotero-updateifs#25]
1.一些期刊依然（中英文都有）查询不到，例如 Science of the Total Environment，唯问中可以查到，但是插件查询不到
2.唯问现在好像加入了频率限制。 每次从easy版换回唯问版时候，习惯将这段时间的文献重新匹配信息，今天批量更新了几篇文献就被封了IP。该问题有可能导致使用者在批量抓取时被封禁IP，大佬看看需不需要调整一下

**Comment by redleafnew** [comment]
![1125172640](https://user-images.githubusercontent.com/22135631/203946592-b7b51b64-242d-43ec-a556-464d674b1ea7.gif)
1. 我这可以。
2. 最好不要批量搞，这样对网站也不公平，爬虫类的程序本来就在法律的边缘。

**Comment by Chikit-L** [comment]
> ![1125172640](https://user-images.githubusercontent.com/22135631/203946592-b7b51b64-242d-43ec-a556-464d674b1ea7.gif) [ ![1125172640](https://user-images.githubusercontent.com/22135631/203946592-b7b51b64-242d-43ec-a556-464d674b1ea7.gif) ](https://user-images.githubusercontent.com/22135631/203946592-b7b51b64-242d-43ec-a556-464d674b1ea7.gif) [ ](https://user-images.githubusercontent.com/22135631/203946592-b7b51b64-242d-43ec-a556-464d674b1ea7.gif)
> 
> 1. 我这可以。
> 2. 最好不要批量搞，这样对网站也不公平，爬虫类的程序本来就在法律的边缘。

很神奇，我这里有一些文献好久都没有办法更新信息了。像 地球与环境、中国岩溶、干旱区资源与环境、水土保持学报、桂林理工大学学报。英文出现问题的机率还小一点，中文期刊出现问题比较多。之前一直以为是插件的问题，现在看来是我这边的问题了。

**Comment by redleafnew** [comment]
我试了你说的两个中文期刊，地球与环境、干旱区资源与环境可以更新。

**Comment by Chikit-L** [comment]
> 我试了你说的两个中文期刊，地球与环境、干旱区资源与环境可以更新。

谢谢大佬了，可能是我这里不知道哪个地方出现问题了😭
