### ISSUE TITLE
使用中遇到的一点小问题

### ISSUE THREAD

**Issue by szk777** [redleafnew/zotero-updateifs#26]
1.如果期刊名称全部是大写的会更新不了期刊信息。
2.没有这个期刊是SCI还是EI的信息。
除此之外就都挺好，解决了使用zotero科研时的一些痛点，让人感觉很舒服。非常感谢。

**Comment by redleafnew** [comment]
1. 给个期刊名称，我试一下。
2. EI信息唯问上没有，影响因子查询、数据目录，配置目录及其它小工具：https://github.com/redleafnew/zotero-updateifsE  easyscholar版的有。

**Comment by szk777** [comment]
1.比如 IEEE JOURNAL OF SOLID-STATE CIRCUITS
2.之前用easyscholar版，我发现easyscholar把我们领域SCI的顶刊写成了EI，然后我就没用了。

**Comment by redleafnew** [comment]
还是把大小写改为Title Case吧，修改程序可能会引起其它问题，可以使用https://getquicker.net/Sharedaction?code=43dcfb1c-fc26-4d38-4c67-08dacf1b610d 动作在Zotero中修改。
