### ISSUE TITLE
自动更新失效

### ISSUE THREAD

**Issue by Chauncy-Eliot** [redleafnew/zotero-updateifs#27]
拖入文献的时候，自动更新显示失败，手动更新可以，中英文文献都是这样，请问是我这边的问题吗

**Comment by redleafnew** [comment]
还是把大小写改为Title Case吧，修改程序可能会引起其它问题，可以使用https://getquicker.net/Sharedaction?code=43dcfb1c-fc26-4d38-4c67-08dacf1b610d 动作在Zotero中修改。

**Comment by redleafnew** [comment]
已修复，但是在自动更新时会有很多提示，我也不知道怎么解决。

**Comment by redleafnew** [comment]
重复提示已经修复。

**Comment by Chauncy-Eliot** [comment]
感谢！
