### ISSUE TITLE
Justscience官网已经恢复和更新了网站

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [redleafnew/zotero-updateifs#28]
Justscience官网这两天刚恢复网站，大佬有空的时候可以给插件重新适配下最新的Justscience官网嘛，万分感谢，辛苦啦

**Comment by redleafnew** [comment]
我这现在可以用啊，是最新版本的插件吗？
如果不行可以试试easyScholar版本的。
影响因子查询、数据目录，配置目录及其它小工具：https://github.com/redleafnew/zotero-updateifsE

**Comment by yuzixieshouhuajiaqi** [comment]
> 我这现在可以用啊，是最新版本的插件吗？ 如果不行可以试试easyScholar版本的。 影响因子查询、数据目录，配置目录及其它小工具：https://github.com/redleafnew/zotero-updateifsE

英文文献可以，中文文献不行，刚刚又手动查了几个文献的期刊，发现Justscience官网又打不开了，是不是查询量稍微大一些，这个网站就会屏蔽IP呀--

**Comment by redleafnew** [comment]
中文的也可以。
屏蔽我也没有办法，可以触动了网站的什么机制吧。

**Comment by yuzixieshouhuajiaqi** [comment]
大佬，你那边现在可以打开Justscience官网嘛，我用不用梯子都打不开

**Comment by yuzixieshouhuajiaqi** [comment]
我又试了一下，全局模式可以打开，真的被这个网站封IP了

**Comment by redleafnew** [comment]
可以打开。
不要批量获取，估计网站启用了防爬虫的机制。

**Comment by yuzixieshouhuajiaqi** [comment]
好的，万分感谢

**Comment by yuzixieshouhuajiaqi** [comment]
我又拿新Ip试了一下，一次更新10个文献的期刊信息就被封IP了，这还咋用，以后只能手动查嘛╯︿╰

**Comment by redleafnew** [comment]
56ec0f647dfecce31ea7f1517ea3fe785908cd40
批量查询时条目之间增加了随机时间，其他的方法我就不知道了。

**Comment by redleafnew** [comment]
更新后还存在这些问题吗？
