### ISSUE TITLE
一次查询几个期刊信息就被封IP，只能手动单个查询

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [redleafnew/zotero-updateifs#29]

**Comment by yuzixieshouhuajiaqi** [comment]
大佬，可以增加一个设置查询间隔时间的选项嘛，比如选中几十条条目后，会自动5秒左右查询一条期刊信息，这样应该不会封IP了吧，不然只能手动一条条去反复查询，效率太低了

**Comment by redleafnew** [comment]
是用的最新版吗？
现在已经添加了条目之间间隔了随机的2～20s的时间了。

**Comment by yuzixieshouhuajiaqi** [comment]
是用的最新版，只要每次选中五六个查询就会被封IP

**Comment by redleafnew** [comment]
那我把时间再延长到5～50s，其他就没有办法了。

**Comment by yuzixieshouhuajiaqi** [comment]
好的，感谢，可以添加一个按钮让大家自己设置间隔时间范围嘛，这样大家可以试错

**Comment by redleafnew** [comment]
不搞那么麻烦了，现在两个条目是随机时间等待。
212eb280263c1f3950a468c9e10314fdbe1c3154
