### ISSUE TITLE
建议中科院分区信息使用升级版

### ISSUE THREAD

**Issue by wanyzh** [redleafnew/zotero-updateifs#3]
中科院分区目前存在基础版和升级版，两者同时存在，过渡期为三年，2022年开始将只发布升级版。

**Comment by redleafnew** [comment]
等2022的出来了再更新吧，反正也只是个参考。

**Comment by fredericky123** [comment]
> 等2022的出来了再更新吧，反正也只是个参考。

2022的要到12月份才会更新，2022的好处在于提示了是否是top，比单纯的几区更有参考价值，如果暂时没时间，就等以后再更新吧

**Comment by wanyzh** [comment]
> 

感觉这个改起来应该也不难，我有空了动手试试。

**Comment by fredericky123** [comment]
> > 
> 
> 感觉这个改起来应该也不难，我有空了动手试试。

感觉就是改下升级版和基础版的数据信息的位置，其他都不用动，期待你的pull request

**Comment by wanyzh** [comment]
> > > 
> > 
> > 
> > 感觉这个改起来应该也不难，我有空了动手试试。
> 
> 感觉就是改下升级版和基础版的数据信息的位置，其他都不用动，期待你的pull request

摸鱼时间瞅了下代码，发现用了正则匹配，奈何本菜鸟对正则不熟。
另外，不知道今天为啥在zotero中获取不了分区信息了，我用插件的代码在浏览器窗口也获取不到。

**Comment by redleafnew** [comment]
var items = ZoteroPane.getSelectedItems();
var item = ZoteroPane.getSelectedItems()[0]; 
var pubTitle = item.getField('publicationTitle');
        var url = 'http://sci.justscience.cn/index.php?q=' + 
                    encodeURIComponent(pubTitle) + '&sci=1'; 

     var resp = await Zotero.HTTP.request("GET", url);
        // var parser = new DOMParser();
        // var html = parser.parseFromString(
        //     resp.responseText,
        //     "text/html"
        // );  
return resp
这一步就报错了，Error: 连接至服务器时发生错误。请检查网络连接。不知道什么原因。

**Comment by fredericky123** [comment]
> var items = ZoteroPane.getSelectedItems(); var item = ZoteroPane.getSelectedItems()[0]; var pubTitle = item.getField('publicationTitle'); var url = 'http://sci.justscience.cn/index.php?q=' + encodeURIComponent(pubTitle) + '&sci=1';
> 
> ```
>  var resp = await Zotero.HTTP.request("GET", url);
>     // var parser = new DOMParser();
>     // var html = parser.parseFromString(
>     //     resp.responseText,
>     //     "text/html"
>     // );  
> ```
> 
> return resp 这一步就报错了，Error: 连接至服务器时发生错误。请检查网络连接。不知道什么原因。

手动访问这个网站查询没问题
不会被网站后台屏蔽了吧

**Comment by fredericky123** [comment]
![image](https://user-images.githubusercontent.com/13982749/157827911-f9f66150-965e-4a82-9591-62d6e1068946.png)
话说 我用插件可以正常访问，地区网络问题？

**Comment by wanyzh** [comment]
> ![image](https://user-images.githubusercontent.com/13982749/157827911-f9f66150-965e-4a82-9591-62d6e1068946.png) 话说 我用插件可以正常访问，地区网络问题？

![image](https://user-images.githubusercontent.com/31266986/157828325-0d924260-a81d-47a1-9681-4bc0e197dc81.png)
我这里无论中文还是英文期刊都无法使用

**Comment by fredericky123** [comment]
> > ![image](https://user-images.githubusercontent.com/13982749/157827911-f9f66150-965e-4a82-9591-62d6e1068946.png) 话说 我用插件可以正常访问，地区网络问题？
> 
> ![image](https://user-images.githubusercontent.com/31266986/157828325-0d924260-a81d-47a1-9681-4bc0e197dc81.png) 我这里无论中文还是英文期刊都无法使用

北京地区，中英文都可以正常更新
估计网络不稳定，说不定明天或者晚上就好了

**Comment by wanyzh** [comment]
> > > ![image](https://user-images.githubusercontent.com/13982749/157827911-f9f66150-965e-4a82-9591-62d6e1068946.png) 话说 我用插件可以正常访问，地区网络问题？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/31266986/157828325-0d924260-a81d-47a1-9681-4bc0e197dc81.png) 我这里无论中文还是英文期刊都无法使用
> 
> 北京地区，中英文都可以正常更新 估计网络不稳定，说不定明天或者晚上就好了

测试了下，发现和我挂的梯子有关。关掉梯子，重启zotero问题解决。

**Comment by redleafnew** [comment]
哪本期刊的基础版和升级有区别？我测试一下，除了加top之外？

**Comment by redleafnew** [comment]
好像将小写的Top变为TOP？

**Comment by fredericky123** [comment]
> 哪本期刊的基础版和升级有区别？我测试一下，除了加top之外？

这个还真不清楚，我这边目前测试OK
之前基础版不显示top和小类分区信息，现在能正常显示了

**Comment by wanyzh** [comment]
> > 哪本期刊的基础版和升级有区别？我测试一下，除了加top之外？
> 
> 这个还真不清楚，我这边目前测试OK 之前基础版不显示top和小类分区信息，现在能正常显示了

可以试试Computers and Geotechnics

**Comment by redleafnew** [comment]
确实不一样，现在测试正常。暂关闭此issue。

**Comment by wanyzh** [comment]
今天更新期刊更新，发现已经是升级版了，感谢！

**Comment by redleafnew** [comment]
可以设置是显示升级版还是基础版。
