### ISSUE TITLE
如何清除updateifs产生的数据

### ISSUE THREAD

**Issue by xiaodl813** [redleafnew/zotero-updateifs#33]
您好，我最近准备从updateifs迁移到green frog插件。我看green frog的介绍是将IF等信息存在Extra字段中，但是前者是将IF等信息存在“索书号”等字段中，所以想问一下updateifs是否有清除生成的数据的方法呢？谢谢！

**Comment by redleafnew** [comment]
如果用quicker，可以用它
https://getquicker.net/Sharedaction?code=c652a3ee-a71c-419a-a992-08dab0af50de

或是用代码：

```
 var items = ZoteroPane.getSelectedItems();
   
            for (let item of items) {

                if (item.isRegularItem() && !item.isCollection()) {
                  
                        item.setField('abstractNote', '');  //摘要
                        item.setField('archive', ''); //归档
                        item.setField('archiveLocation', '');  //归档位置
                        item.setField('callNumber', '');  //索引号
                        item.setField('rights', ''); //版权
                        item.setField('series', '');  //系列
                        item.setField('seriesText', '');  //系列文本
                        item.setField('seriesTitle', '');  //系列标题
                        item.setField('libraryCatalog', '');  //图书馆目录
                        item.setField('extra', ''); //其它
                        item.saveTx();

                   
                }
            }
```

**Comment by xiaodl813** [comment]
> 如果用quicker，可以用它 https://getquicker.net/Sharedaction?code=c652a3ee-a71c-419a-a992-08dab0af50de
> 
> 或是用代码：
> 
> ```
>  var items = ZoteroPane.getSelectedItems();
>    
>             for (let item of items) {
> 
>                 if (item.isRegularItem() && !item.isCollection()) {
>                   
>                         item.setField('abstractNote', '');  //摘要
>                         item.setField('archive', ''); //归档
>                         item.setField('archiveLocation', '');  //归档位置
>                         item.setField('callNumber', '');  //索引号
>                         item.setField('rights', ''); //版权
>                         item.setField('series', '');  //系列
>                         item.setField('seriesText', '');  //系列文本
>                         item.setField('seriesTitle', '');  //系列标题
>                         item.setField('libraryCatalog', '');  //图书馆目录
>                         item.setField('extra', ''); //其它
>                         item.saveTx();
> 
>                    
>                 }
>             }
> ```

请问代码是用什么环境运行呢？谢谢

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/228715884-111bb5c3-afae-4074-bbbb-699073d08f31.png)

**Comment by redleafnew** [comment]
如果你打算用Quicker专业版，可以使用我的推荐码：467528-5244，我们两个的时长都可以增加3个月。

**Comment by xiaodl813** [comment]
好的感谢，已经成功清除了，如果作者可以在README或者插件中添加该方法的说明以帮助其他人那就更好了！谢谢！

> 如果你打算用Quicker专业版，可以使用我的推荐码：467528-5244，我们两个的时长都可以增加3个月。

也感谢作者提供的Quicker专业版推荐码，我需要的时候会填写的，谢谢！
