### ISSUE TITLE
更新期刊信息提示成功了，却在extra中并没有显示信息

### ISSUE THREAD

**Issue by MrGongqi** [redleafnew/zotero-updateifs#34]
![image](https://user-images.githubusercontent.com/49467246/230309271-c29b64d5-7cb5-4086-b8eb-d100decfb68f.png)
![image](https://user-images.githubusercontent.com/49467246/230309801-982418b5-fdcc-4c07-bdb8-e2c7d5917dc4.png)
出现了以上的错误，这样一来插件就完全没起作用了，，不知道是为什么，上午的时候还是好好的。

**Comment by redleafnew** [comment]
什么期刊？把条目的CSL JSON格式贴上来试试

**Comment by MrGongqi** [comment]
FUEL,一个能源期刊，可以查到为一区期刊，CSL JSON格式我不知道怎样导出，期刊全名就叫fuel

**Comment by redleafnew** [comment]
条目上右击，导出

**Comment by MrGongqi** [comment]
![image](https://user-images.githubusercontent.com/49467246/230364431-f194e106-b577-441e-b120-923c21f47a84.png)

**Comment by redleafnew** [comment]
把txt贴上来我才可以测试啊

**Comment by MrGongqi** [comment]
[Exported Items.txt](https://github.com/redleafnew/zotero-updateifs/files/11171037/Exported.Items.txt)

**Comment by redleafnew** [comment]
我这没有问题。

在Tools-Developer-Run JS 看看有什么结果，
需要将你的密钥替换为自己的密钥。
![image](https://user-images.githubusercontent.com/22135631/230393946-fdbf8909-1e39-4ccc-9acd-64aab36c4180.png)

```
  var items = ZoteroPane.getSelectedItems();
  var item = items[0]; 
  let secretKey = '你的密钥';
  publicationTitle =encodeURIComponent(item.getField('publicationTitle'));
  var url = `https://easyscholar.cc/open/getPublicationRank?secretKey=${secretKey}&publicationName=${publicationTitle}`;
  let req = await Zotero.HTTP.request('GET', url, { responseType: 'json' });
  return req.response;
```

**Comment by MrGongqi** [comment]
好的

**Comment by redleafnew** [comment]
解决了吗？

**Comment by redleafnew** [comment]
请到这反馈
影响因子查询、数据目录，配置目录及其它小工具, Green Frog：https://github.com/redleafnew/zotero-updateifsE
