### ISSUE TITLE
网页easyschoor能显示出影响因子但是zotero上部分文章无法查到影响因子（期刊信息更新失败）

### ISSUE THREAD

**Issue by vivian53** [redleafnew/zotero-updateifs#35]

**Comment by redleafnew** [comment]
哪个期刊，将条目的csl json格式导出来，粘在这。

**Comment by redleafnew** [comment]
请到
影响因子查询、数据目录，配置目录及其它小工具, Green Frog：https://github.com/redleafnew/zotero-updateifsE
反馈，两个插件不同。
