### ISSUE TITLE
zotero7无法安装最新版

### ISSUE THREAD

**Issue by qwpyyx** [redleafnew/zotero-updateifs#36]
下载最新版的[zotero-updateifs](https://github.com/redleafnew/zotero-updateifs)无法安装，应该是版本不符，请问是否有适配zotero7的版本？

**Comment by redleafnew** [comment]
没有精力更新这个了，可以用影响因子查询、数据目录，配置目录及其它小工具, Green Frog：https://github.com/redleafnew/zotero-updateifsE
