### ISSUE TITLE
适配zotero7可以吗

### ISSUE THREAD

**Issue by QingbaoLi** [redleafnew/zotero-updateifs#38]
目前“zotero更新影响因子”很好的一点就是可以自定义数据存储位置，十分灵活。刚才才发现greenfrog也是作者开发的，真牛逼。
能够把“zotero更新影响因子”更新适配到zotero7吗？用的很顺手，不想换了

**Comment by redleafnew** [comment]
[zotero-updateifs](https://github.com/redleafnew/zotero-updateifs)用到了爬虫，有些风险。暂不准备更新了。Zotero也不推荐字段的借用。GreenFrog可以自定义列。

**Comment by QingbaoLi** [comment]
> [zotero-updateifs](https://github.com/redleafnew/zotero-updateifs)用到了爬虫，有些风险。暂不准备更新了。Zotero也不推荐字段的借用。GreenFrog可以自定义列。

好的，明白了，谢谢！
