### ISSUE TITLE
建议分区信息可自定义填入条目，而不是指定在“其他”中

### ISSUE THREAD

**Issue by S-Kee** [redleafnew/zotero-updateifs#4]
很多插件都会把相关信息填在“其他”中，例如会议论文的doi。建议可以自定义。
另外建议可自定义添加那些分区，不填入哪些分区，只填入自己关心的。
另外建议合并论文的引用数，和期刊影响因子应该算类似的参数。

**Comment by redleafnew** [comment]
太复杂了，只能慢慢来了。

**Comment by redleafnew** [comment]
<img width="90" alt="20220327100710" src="https://user-images.githubusercontent.com/22135631/160263666-10cf177e-9630-4bc5-9d3d-4e4fb9373488.png">
把这五个项目分别填入这五个字段中？

**Comment by redleafnew** [comment]
已经更新，可以分别设置。

**Comment by led-ury** [comment]
自定义能让都选“其他”吗，只有“其他”能单个字段填入所有信息

**Comment by redleafnew** [comment]
具体什么意思，将所有信息都填入“其他”中，像以前版本一样？

**Comment by led-ury** [comment]
是的

**Comment by redleafnew** [comment]
源代码已上传，可以自行包测试。我过段时间打包。

**Comment by redleafnew** [comment]
<code>extensions.updateifs.sci-all-extra</code> // 显示所有英文期刊信息到其它
    <code>extensions.updateifs.chj-all-extra</code>  // 显示所有中文期刊信息到其它
需要在Zotero中的Edit-Preference-Advanced-Config Editor中将上述两个值设置为true (默认为false)

**Comment by XiaoNingxi** [comment]
您好，我用的zotero beta版6.0.12-beta.2+fc0f6157d，不可以设置在“其他”字段了，是因为beta版本原因嘛？

**Comment by redleafnew** [comment]
影响因子查询、数据目录，配置目录及其它小工具：https://github.com/redleafnew/zotero-updateifsE
试试这个

**Comment by XiaoNingxi** [comment]
非常感谢！！可以了
