### ISSUE TITLE
关于影响因子小数点位数

### ISSUE THREAD

**Issue by Torstudio** [redleafnew/zotero-updateifs#42]
您好，影响因子小数点位数显示出来有4位了，有点太多了，如果喜欢将影响因子添加到列表抬头时，会显示更加杂乱，我认为最多显示一位小数点就可以了，建议修改。

**Comment by redleafnew** [comment]
哪个期刊保留这么多，把条目JSON格式上传上来看看。

**Comment by Torstudio** [comment]
我全部更新了一下后，刚看了一下，恢复3个小数点了。开始不知道怎么回事，有3个小数点也有4个小数点的。但是现在3个小数点是不是还是有点多

**Comment by Torstudio** [comment]
![20231202 119](https://github.com/redleafnew/zotero-updateifs/assets/137071717/3344676b-d708-46de-b0cd-2cb7acd47a4b)
昨天截图中终于找到一个四位小数点的。在索书号和版权这里。

**Comment by redleafnew** [comment]
影响因子查询、数据目录，配置目录及其它小工具, Green Frog：https://github.com/redleafnew/zotero-updateifsE 用这个吧，到Zotero 7时本插件就不兼容了。

**Comment by Torstudio** [comment]
绿娃不知道为什么不兼容。ifs同样也不兼容，只有updateifs兼容

**Comment by redleafnew** [comment]
怎么不兼容，看看readme下载合适的版本，最新版本只兼容Zotero 7

**Comment by Torstudio** [comment]
谢谢！已经下对green frog了，原来可能没下对版本
