### ISSUE TITLE
分区信息会影响citation counts信息

### ISSUE THREAD

**Issue by xuey06** [redleafnew/zotero-updateifs#5]
能否设置分区信息在追加在“其它”中的已有信息后面？
否则会影响citation counts的引用信息的显示

**Comment by redleafnew** [comment]
1. 可以在插件中设置，将JCR显示在其它没有用到的字段。
2. 也可以修改高级设置，在Zotero点击，编辑-首选项-高级-设置编辑器-输入 extensions.updateifs.jcr-qu-field，如设置的值为extra，则会显示在Extra中，但会估计覆盖以前的内容。
3. 上个版本都是显示在Extra中的，而且不会覆盖其它内容。

**Comment by xuey06** [comment]
Thanks
