### ISSUE TITLE
Ieee & Iet期刊名小写时无法识别

### ISSUE THREAD

**Issue by MikeChanV8** [redleafnew/zotero-updateifs#6]
Ieee&Iet期刊名小写时无法识别
![image](https://user-images.githubusercontent.com/71354849/161680418-13d63698-a37e-4b89-b73b-b661748c2f7b.png)
改为大写后能识别
![image](https://user-images.githubusercontent.com/71354849/161680512-eed212f8-4441-49eb-b083-63401c3d21a2.png)

**Comment by redleafnew** [comment]
是严格匹配大小写的。
