### ISSUE TITLE
能否匹配带逗号和冒号的期刊？

### ISSUE THREAD

**Issue by crazyi** [redleafnew/zotero-updateifs#7]
例如：
Earth, Planets and Space在维问中的名字为：Earth Planets and Space
Journal of Geophysical Research: Solid Earth在维问中的名字为：Journal of Geophysical Research-Solid Earth
这个理论上应该比较好处理，我看了下插件中好像有处理期刊名带&的代码，应该可以类似修改吧
抱歉不是太懂js没法自己修改

**Comment by redleafnew** [comment]
把期刊中的逗号和冒号删除后就可以匹配上了吗？

**Comment by crazyi** [comment]
我觉得理论上应该是的吧，看了下详细页及其网址都是把逗号去掉，冒号+空格改成了-

**Comment by redleafnew** [comment]
你先把期刊名称修改一下（去逗号，冒号+空格改为-），看能不能行？可以的话我再修改源代码

**Comment by redleafnew** [comment]
好的，我回头修改一下，应该不难。

**Comment by crazyi** [comment]
另外最新的0.9.1版貌似有bug，每次都只有重新打开zotero的第一次更新才能更新if，再次更新if只能重新打开if，0.8.0版没问题

**Comment by redleafnew** [comment]
谢谢。我也搞不清楚是哪的问题。确实存在。

**Comment by redleafnew** [comment]
更新了，我试着可以了。

**Comment by crazyi** [comment]
多谢，标题的问题解决了，但是非首次无法更新的问题还在，我把新加的替换代码合并到0.8.0去

**Comment by redleafnew** [comment]
这个问题搞清楚是哪的原因。在开发论坛上问了，没有人理。

**Comment by crazyi** [comment]
还有个小问题，我看了下代码用的是replace函数，但是这个函数有个问题就是只替换一次，所以对杂志名中有多个&,:这类字符的无效，例如这个杂志：[Earth, Moon, and Planets](https://link.springer.com/article/10.1007/s11038-022-09545-7)，我试着把replace函数改成replaceAll函数，貌似无效

**Comment by crazyi** [comment]
另外我还想把中文的（）替换为英文的()，貌似也不成功，不知道什么问题，下面是我添加的代码：
`replace('（', '\\(').
    eplace('）', '\\)'); // 替换括号`

**Comment by crazyi** [comment]
> 这个问题搞清楚是哪的原因。在开发论坛上问了，没有人理。https://groups.google.com/g/zotero-dev/c/17z3Lq8C7tI

建议去https://forums.zotero.org/问一下，那里的回复速度挺快的

**Comment by redleafnew** [comment]
论坛上问过，但开发人员说涉及代码的需要到开发者论坛上提问，

**Comment by redleafnew** [comment]
> 另外我还想把中文的（）替换为英文的()，从替换结果来看应该是成功了，但是更新还是失败，不知道什么问题，下面是我添加的代码：
> 
> * replace("（", "(").
> * replace("）", ")"); // 替换括号

也给个例子吧。

**Comment by redleafnew** [comment]
> 还有个小问题，我看了下代码用的是replace函数，但是这个函数有个问题就是只替换一次，所以对杂志名中有多个&,:这类字符的无效，例如这个杂志：[Earth, Moon, and Planets](https://link.springer.com/article/10.1007/s11038-022-09545-7)，我试着把replace函数改成replaceAll函数，貌似无效
> 
> 这个问题已经解决了
> 
> * replace(/&/g, 'and').  // 替换&为and
> * replace(/ - /g, '-').
> * replace(/,/g, '').    // 替换逗号（，）
> * replace(/: /g, '-');  // 替换冒号空格（：）

这个解决了是吧。

**Comment by redleafnew** [comment]
> 另外我还想把中文的（）替换为英文的()，从替换结果来看应该是成功了，但是更新还是失败，不知道什么问题，下面是我添加的代码：
> 
> * replace("（", "(").
> * replace("）", ")"); // 替换括号

可以在Zotero的JavaScript窗口试验，用替换后的题目到唯问上试试。

**Comment by crazyi** [comment]
我是刚入门了一下js，在浏览器中调试后看到标题已经是替换成功了，但是更新不行
测试文章：https://chn.oversea.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFD&filename=WHCH201212011
貌似新版的知网已经把括号都改成英文的了，我抓取的估计是老版的，还是中文括号
![QQ20220415-080222@2x](https://user-images.githubusercontent.com/1018370/163495381-413bf500-b9c2-4c19-8878-bce778b67ba2.jpg)

**Comment by redleafnew** [comment]
找个中文括号的例子？你的测试网页好像也是英文括号的。

**Comment by redleafnew** [comment]
那找到再说吧。
