### ISSUE TITLE
windows端期刊信息全部更新失败

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [redleafnew/zotero-updateifs#9]
之前成功过一次，清除字段后，重新更新期刊信息，就全部失败了

**Comment by redleafnew** [comment]
可以提供一下条目吗？或是参考文献的网址。

**Comment by yuzixieshouhuajiaqi** [comment]
上午全部更新失败，中午又试了一次，部分成功，期刊的模糊匹配功能感觉不太完善，同一期刊名字，大小写不同就导致更新失败，手动修改之后就都更新成功了，还有很多不规范的期刊名称导致更新失败，比如长短连字符的不同，and和&的不同，the有没有等等

**Comment by yuzixieshouhuajiaqi** [comment]
可以参考这里面提交的期刊匹配失败的例子，总结出一些规律，https://gitee.com/qnscholar/zotero-if-pro-max/issues/I5007Z

**Comment by redleafnew** [comment]
插件的数据来源于 http://sci.justscience.cn/  上面那个帖子很长，还是提供一下条目吧。

**Comment by yuzixieshouhuajiaqi** [comment]
[导出的条目.csv](https://github.com/redleafnew/zotero-updateifs/files/8646482/default.csv)

**Comment by redleafnew** [comment]
这么多条目都不行？



Best regards!

Sincerely,
Minyi Han
No 1#, Weigang, Nanjing, 210095, P. R. China
College of Food Science & Technology
Nanjing Agricultural University 
 
发件人： yuzixieshouhuajiaqi
发送时间： 2022-05-08 14:43
收件人： redleafnew/zotero-updateifs
抄送： redleafnew; Comment
主题： Re: [redleafnew/zotero-updateifs] windows端期刊信息全部更新失败 (Issue #9)
导出的条目.csv

**Comment by yuzixieshouhuajiaqi** [comment]
[导出的条目.csv](https://github.com/redleafnew/zotero-updateifs/files/8646492/default.csv)
对，这是另外一个插件能识别的，但是zotero-updateifs不能识别

**Comment by yuzixieshouhuajiaqi** [comment]
我觉得期刊全称几个单词的首字母大小写不能模糊匹配是第一个需要解决的问题，其次就是一些不规范期刊名称的模糊匹配了，比如长短连字符的不同，and和&的不同，the有没有等等

**Comment by redleafnew** [comment]
无法在Zotero中导入。
加入Zotero群组，拖条目到群组中吧。
https://www.zotero.org/groups/4683725/plugin-test

**Comment by yuzixieshouhuajiaqi** [comment]
刚才试了其他几种格式，github上无法上传

**Comment by redleafnew** [comment]
> 我觉得期刊全称几个单词的首字母大小写不能模糊匹配是第一个需要解决的问题，其次就是一些不规范期刊名称的模糊匹配了，比如长短连字符的不同，and和&的不同，the有没有等等

模糊匹配不打算做，还是要规范，否则后面引用的时候也是错误的。
and 和 &是支持的好像。

**Comment by redleafnew** [comment]
不需要那么多条目，只需要典型的，每个类型1,2个条目即可。

**Comment by yuzixieshouhuajiaqi** [comment]
抱歉，没时间整理了，学业很忙，如果能做到通过插件模糊匹配获取到规范的期刊全称和简称，并覆盖条目中不规范的期刊全称和简称，肯定能碾压同类功能的其他插件
